[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

src_filter =
  +<main.cpp>

lib_deps =
  milesburton/DallasTemperature
  paulstoffregen/OneWire
  adafruit/Adafruit SSD1306
  adafruit/Adafruit GFX Library
  adafruit/RTClib
